### ISSUE TITLE
Give pip_run.read-deps an option for newline-terminated output

### ISSUE THREAD

**Issue by jwodder** [jaraco/pip-run#53]
Feature request: Give `python -m pip_run.read-deps` a `--newline` (or whatever you want to call it) option that would cause the individual requirements to be output on separate lines.  This would make it easy to create `requirements.txt` files for `__requires__`-using scripts, especially when dealing with requirements with markers like `importlib-metadata>=3.6; python_version < "3.10"`, which are currently output with spaces embedded, making it difficult to separate them from adjacent requirements.

**Comment by jaraco** [comment]
SGTM. Maybe instead of `--newline`, consider something like `--separator` or `--sep`, which could take an arbitrary separator like `newline` or `0x10` or `\n` or even `\0` (null character), so it could be passed to something like `xargs -0`.

I'm not sure we need to support all forms of newline, maybe just one or two. Maybe propose your best instincts and we'll work from there.

**Comment by jwodder** [comment]
I'd say the most commonly-desired separators are space, newline, and NUL, and it's not really worth it to support any others (aside from maybe JSON output?).  If I were choosing the command-line options, I'd add `-n`/`--nl`/`--newline` for newline and `-0`/`--null` for NUL, and have later options override earlier, but I don't know how you'd pull that off with autocommand.

**Comment by jaraco** [comment]
In #54, I illustrate how a `separator` argument has the simple elegance of providing a single option that meets all of the above uses and possibly more. `-s newline` is a bit more to type than `--newline`, but is straightforward to implement and avoids the extra logic that would be required to deal with the conflicts between options. WDYT?

**Comment by jwodder** [comment]
@jaraco Acceptable.
