### ISSUE TITLE
double-dash is irritating, especially for script invocation

### ISSUE THREAD

**Issue by jaraco** [jaraco/pip-run#57]
In https://github.com/pypa/pip/issues/3971#issuecomment-1320927420, @pfmoore has to say: 

> I find having to include the `--` to separate the command parameters clumsy, and I'm not in love with details like the default being to print all of pip's output. Which all adds up to a general sense of "I never think to use it, because it's _sort of_ alright, but irritating". Sorry, I know that's annoyingly vague, and I do think that the UI is the hardest part of this to get right. What I _want_ is to be able to type `pip-run my_script.py arg1 arg2 arg3`, and have it run my script with all dependencies available. The other features of `pip-run` are secondary (to me).

In this issue, I'll focus on the double-dash behavior.

The reason for the `--` is to clearly separate the parameters to the script from parameters to pip/pip-run. Since there are two concerns to deal with here, there needs to be clear separation. For me, 95% of the usage is on the install parameters side, with the right hand side accepting any argument to Python (sometimes no args (for a repl), sometimes `-c`, sometimes `-m`, and sometimes a script). This generalization means the tool has a wide variety of applications.

I'd like to improve the reported scenario, but I struggle a bit with how to do that without drastically degrading the current experience.

One possible improvement could be to allow the `--` to be optional in the specific case where a script is the first parameter. That is, if the first parameter is an extant file, that's not a valid parameter to `pip install`, so `pip-run` could infer a `--` before it. If someone wanted to pass arguments to the interpreter or to pip, they would need to bring back the `--`, but for convenience, a simple script invocation could omit it. WDYT?

**Comment by pfmoore** [comment]
I find the UI of `pipx run` to be better - `pipx run <pipx options> script name <script args>`. I know `pip-run`'s option structure makes an arrangement like that harder, but I think it's worth it. But by collecting everything before `--` and passing it to pip, you've made it tricky to determine where the break point is, *except* by some sort of explicit marker. At least not without making a backward incompatible change to the option structure.

I will say that I don't particularly expect `pip-run` to "fix" any of this. I think we're still (to an extent) exploring the whole "how to run scripts with dependencies" area, and I don't think there's any one good answer at the moment. So competing approaches aren't necessarily a bad thing.

Having said that, assuming https://github.com/pypa/pipx/pull/916 lands, I'll probably use `pipx run` for most of my "run a script with dependencies" needs in the future.

**Comment by jaraco** [comment]
One of the things pip-run allows is to run with different versions of pip, something I've used innumerable times:

```
pip-run pip==19.0.1 -- -m pip install setuptools==50.0.0
```

And similarly for pip-run itself (which was more likely used because I probably don't want to install setuptools):

```
pip-run pip==19.0.1 -- -m pip-run setuptoools==50.0.0
```

The ability here to pass parameters to pip run/install in two different contexts is crucial. That's what led me to the explicit marker.

It's immensely useful and generalizable for pip run to accept two sets of parameters, one to pip install and the other to a python interpreter. As currently implemented, `pip-run` doesn't accept any parameters for itself (other than `--help` for obvious reasons).

> Having said that, assuming [pypa/pipx#916](https://github.com/pypa/pipx/pull/916) lands, I'll probably use `pipx run` for most of my "run a script with dependencies" needs in the future.

`pip-run` has a vested interest in serving this use-case, especially if it makes a difference between having integration with pip and not. I'm happy for you to adopt pipx (in fact elated; the more the merrier) as long as it doesn't distract from the value that `pip-run` is attempting to demonstrate for a pip subcommand.

> I find the UI of `pipx run` to be better - `pipx run <pipx options> script name <script args>`.

That's interesting. That suggests you think that `pip-run` could even do something more sophisticated - that it should be able to detect a script name _anywhere_ in the initial options and if it detects one, use that as the pivot.

That still exposes a weakness in `pipx` w.r.t. `pip-run` - options to the Python interpreter aren't allowed - only options to pipx and the script are allowed (no `-W` or `-s`, which I've used frequently).

What if pip-run instead used a heuristic to determine the best pivot between pip install args and python args and then that routine could be arbitrarily complicated? Currently, it relies on an explicit `--` separator, but in lieu of that, it could infer which parameters appear to be relevant to pip install and at the first one that's not a match, assume the parameters are for Python.

**Comment by pfmoore** [comment]
> One of the things pip-run allows is to run with different versions of pip, something I've used innumerable times:

That's not something I've ever needed to do. Now that you've explained it, I can see the value, and I can see how the existing CLI syntax enables it, but I can't make myself love a syntax that is as hard to understand as those examples are to me.

Don't take this the wrong way, but the command line syntax for `pip-run` seems designed more around the needs of the implementation than the needs of the user. From an implementation perspective, `pip-run <stuff1> -- <stuff2>` is obvious - you pass `<stuff1>` to pip, and then `<stuff2>` to Python[^1]. But that leads to the user, when trying to work out "how do I do X?" having to break the task down into those implementation steps - "what do I want pip to do" and "how do I then do X using Python" - in order to construct the command line they want. That's fundamentally my problem with the UI here - it's not designed with the user in mind (or maybe it's designed with *one* user, you, in mind...)

> It's immensely useful and generalizable for pip run to accept two sets of parameters, one to pip install and the other to a python interpreter.

Maybe it is, but it's not (IMO) particularly user-friendly.

Now that I look at the UI from this perspective, it seems to me that `pip-run` is useful as an "advanced" tool for specialist users, but it's not really going to work for casual users, beginners or non-programmers - all of whom use pip in one form or another. So maybe it's fine as a standalone tool for people who need it, but wouldn't work as a pip subcommand, because "dumbing down" the UI would destroy its value as a specialist tool.

> That's interesting. That suggests you think that pip-run could even do something more sophisticated - that it should be able to detect a script name anywhere in the initial options and if it detects one, use that as the pivot.

`pipx run` doesn't allow arbitrary options before the script and its arguments. The arguments passed to pip are supplied as the *value* of the pipx option `--pip-args`. So pipx can simply take "the tail of the argv list" as the script and its arguments (using the argparse `nargs=argparse.REMAINDER` parameter for the argument).

I don't know how, or if, `pip-run` would do something similar. Doing so without a bacwards incompatible change to argument parsing is likely to be very difficult. But again, that's about whether the UI should be designed around end user use cases, or technical capabilities[^2].

> That still exposes a weakness in pipx w.r.t. pip-run - options to the Python interpreter aren't allowed

Well, `pipx run` isn't intended to run an arbitrary Python interpreter command line. I wouldn't characterise that as a "weakness", but rather as a "design choice".

> What if pip-run instead used a heuristic to determine the best pivot between pip install args and python args and then that routine could be arbitrarily complicated?

That's *still* focusing on the "split into pip bits and python bits" model, so I'm not sure it helps. There's a fundamental design disagreement, and in many ways I think it does the `pip-run` model a disservice to patch over this one aspect simply to make it more palatable to people with very different expectations.

[^1]: It may well say something about how `pip-run` is documented that this very straightforward model of what's going on wasn't more obvious to me before now. But of course documenting it from that point of view would move the emphasis away from "what can this tool do for you", which has its own drawbacks...
[^2]: And I'm not trying to judge here. IMO there are valid arguments for both types of UI, they just serve very different user bases.

**Comment by jaraco** [comment]
> The arguments passed to pip are supplied as the _value_ of the pipx option `--pip-args`

When initially drafting pip-run (rwt at the time), I considered this option, but in my experience, any command that takes a full command line as an argument leads to a bad experience, because it requires quoting and escaping and is highly sensitive to shell-specific behaviors (where to put the quotes, what escapes to use, what if those commands have nested args). For an extreme example, consider:

```
sudo sh -c "pip-run --pip-args='tempora -r c:\foo\requirements.txt --install-option=\"--install-scripts=c:\scripts\"' my_script.py"
```

I've mixed some use-cases for illustration, and I'm almost certain that command is broken because I'm unsure how to escape everything properly. In fact, there may not be a proper way to format that command in a way that's portable and would run on Powershell and bash (let alone xonsh).

I saw the `--` separator as a pragmatic way to dramatically simplify the syntax and improve the user experience (by avoiding any new options.

> Now that I look at the UI from this perspective, it seems to me that `pip-run` is useful as an "advanced" tool for specialist users, but it's not really going to work for casual users, beginners or non-programmers - all of whom use pip in one form or another. So maybe it's fine as a standalone tool for people who need it, but wouldn't work as a pip subcommand, because "dumbing down" the UI would destroy its value as a specialist tool.

To the contrary, pip-run introduces very little specialized behavior. It acts as a fairly lightweight wrapper around pip and python, which if you're a CLI python developer, you probably already have experience with at least the basics. And because it builds on these well-known interfaces (and minimally affecting them), skills and experience from those tools transfer naturally.

Moreover, this tool also serves as a communications mechanism, allowing an experienced specialist to craft a clever pip-run command that they can pass to a novice and that they can just run (as long as they have pip-run available). And because it's stateless, the expert doesn't need to caveat or provide context about prep or teardown.

It provides very simple semantics for concise basic usage (`pip-run requests` or `pip-run -- myscript.py`), but also provides unlimited re-use through its simple primitives.

I've never meant for it to be an advanced tool, but instead as a convenience wrapper for some very common but often short-lived use cases. Where I've found it most useful is in communicating a bug repro, because it does in one command something that often takes several.

---

I'd also like to point out that pip-run is a library and can be re-purposed. The default entry point is super simple:

https://github.com/jaraco/pip-run/blob/aa9c2ae20e2257f3a05cb1abd33137664229d2b4/pip_run/__init__.py#L9-L19

Anyone is free to re-envision the user experience by combining those primitives in a different way. For example, one could have `pip-run-script` which accepts `--pip-install-args` and assumes parameters are for the script invocation.

---

For this bug, I'd like to focus on ways to alleviate the need for `--` in simple use cases. I think by detecting the presence of an existing python file in the command line should be sufficient to infer "not pip args".
